spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    jdbc-url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        sql: debug

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

constant-data:
  modification-limit-value: 0
  modifiable-date-value: 10
